### ISSUE TITLE
Good Work, But Small Bug Exists.

### ISSUE THREAD

**Issue by SugarRuy** [tianyic/only_train_once#1]
Hi Tianyi, 

There is a small bug in `train/run_cnn.py` that prevents me from running your training code. I have fixed it and it runs great. I hope you could take a look and fix it. 

In line 20, `from optimizer import HSPG, ProxSG` should be replaced with `from optimizer import HSPG`, otherwise an `ImportError: cannot import name 'ProxSG' from 'optimizer'` will happen. 

In line 96, `exit()` should be deleted or commented, otherwise, the training process will not start but exit. 

Thanks for your contribution to open source.

**Comment by tianyic** [comment]
Thanks for pointing it out! The bug will be fixed  in the following days.
