### ISSUE TITLE
OTO on detection models

### ISSUE THREAD

**Issue by LishaTang** [tianyic/only_train_once#16]
Hi, thanks for your work. Have u tried OTO on detection models, like the YOLO series? And is it possible for you to release a tutorial about that in the future? Thanks.

**Comment by tianyic** [comment]
Thanks for the question. 

We have conducted on similar scenarios, such as FaceDetection, and get very promising results.  In some issues, people have applied OTO onto some YOLO tasks. We will provide official tutorials upon our bandwidth. The key of applying OTO would be if the backbone of YOLO has not unsupported operators. Some architecture such as resnet101, darknet in https://github.com/dbolya/yolact/  should be definitely fine, but some may need a little bit architecture adjustment. See https://github.com/tianyic/only_train_once/issues/5
