### ISSUE TITLE
Protocol Buffer Version Conflict with local

### ISSUE THREAD

**Issue by gaoxueyi0532** [tianyic/only_train_once#20]
[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.1).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.1).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
Aborted (core dumped)

**Comment by tianyic** [comment]
Thanks for reaching out. The error information looks irrelevant to the library. Please provide detailed reproducing steps. We will see if it is possible to fix it on our side.

**Comment by tianyic** [comment]
Closed due to no reproducing responses.
