### ISSUE TITLE
some confuse about Algorithm-3

### ISSUE THREAD

**Issue by gaoxueyi0532** [tianyic/only_train_once#25]
please explain the function Lines 9-10 of Algorithm-3 in detail, thanks very much!

**Comment by tianyic** [comment]
Thanks for the question. In short, line 9-10 is a Half-Space projector proposed in the HSPG paper https://arxiv.org/abs/2009.12078 with more rigorous theoretical guarantee in a following theoretical paper https://openreview.net/pdf?id=KBhSyBBeeO. Its general goal is to effectively project a group of variables onto zero (produce group sparsity) and avoid objective function value regression as much as possible.
