### ISSUE TITLE
How to compress the backbone of a model with an auxiliary branch？

### ISSUE THREAD

**Issue by wangxd15** [tianyic/only_train_once#29]
Very nice work !
I am compressing a model with a backbone and an auxiliary branch, but hope to keep the auxiliary branch unpruned. Does OTO support such operations and  how to set? Thanks

**Comment by tianyic** [comment]
@wangxd15 This is a good question. 

We have ongoing plan to support it more conveniently in the future releases after completing current [working items](https://github.com/tianyic/only_train_once#working-items).

For a short-term fix, you could print out the dependency graph, and find the connected components corresponding to the auxiliary branches. Then manipulate the type for these connected components as `GROUP_TYPE['default]` which would be skipped from being pruned. In particular, edit the `cc_param_groups['group_type'] = GROUP_TYPE['default]` in `param_groups()` function of `Graph` class
