### ISSUE TITLE
Problem with compress model

### ISSUE THREAD

**Issue by bnomq** [tianyic/only_train_once#32]
Thanks to share codes.
but I met a problem with compressing some model.
I have an error message when I test code below.

attentionNet [[network](https://github.com/sharif-apu/BJDD_CVPR21/tree/main/modelDefinitions)]
```python
import numpy as np
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter
import torch.nn.functional as F
from only_train_once import OTO
from modelDefinition.attentionGen import attentionNet

model = attentionNet()
dummy_input = torch.zeros(1, 3, 128, 128).cuda()
oto = OTO(model=model, dummy_input=dummy_input)
oto.visualize_zigs(view=False)
oto.random_set_zero_groups() # Randomly set a subset of ZIGs to be zero.
oto.compress()

``` 

Error massage 
```
workspace/only_train_once/only_train_once/graph/graph.py", line 377, in compress
    pruned_onnx_param = numpy_param[:, incoming_cc.non_zero_group_idxes, ...]
IndexError: index 1 is out of bounds for axis 1 with size 1
```

So I add code like this, and pass the code.
Is this make sense?
```python
#only_train_once/only_train_once/graph/graph.py#
filtered_non_zero_group_idxes = [x for x in incoming_cc.non_zero_group_idxes if x < numpy_param.shape[1]]
incoming_cc.non_zero_group_idxes = filtered_non_zero_group_idxes
``` 

Please let me know how to solve the problem, thank you.

```
torch     1.13.0
only-train-once     2.0.13
onnx     1.13.1
```

**Comment by tianyic** [comment]
@bnomq Thanks for the question. 

I would assume the attentionnet has some multi-head attention layers, which operator are not fully supported in the current OTOv2. Please await for our coming OTO-LLM release where we will support LLAMA attention etc.

**Comment by tianyic** [comment]
The refactorized OTO has been released. Feel free to retry the new version to see if the network can be supported. Thanks.
