### ISSUE TITLE
When quantizing the YOLOv8 model and calling the code optimizer = oto.dhspg(), an error is thrown.

### ISSUE THREAD

**Issue by Gooddz1** [tianyic/only_train_once#38]
When quantizing the YOLOv8 model and calling the code optimizer = oto.dhspg(), it throws an error:
 "Traceback (most recent call last): File "yolov8_test.py", line 32, in <module> optimizer = oto.dhspg( File "/home/sta/ldz/project/quantization/yolov8/only_train_once/only_train_once/init.py", line 42, in dhspg self._optimizer = DHSPG( File "/home/sta/ldz/project/quantization/yolov8/only_train_once/only_train_once/optimizer/dhspg.py", line 62, in init super(DHSPG, self).init(params, defaults) File "/home/sta/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in init raise ValueError("optimizer got an empty parameter list") ValueError: optimizer got an empty parameter list".

**Comment by Gooddz1** [comment]
When using model = resnet18_cifar10() and calling the code optimizer = oto.dhspg(), it does not throw an error.

**Comment by tianyic** [comment]
Thanks for reaching out. We have an internal OTO version that will be released by the end of this month. The internal version has significantly major updates and improvements. Please retry on that if possible. @Gooddz1
