### ISSUE TITLE
Interested in OTOV2 work

### ISSUE THREAD

**Issue by qgh1223** [tianyic/only_train_once#4]
I'm interested in your new work. Hope your code will come soon

**Comment by tianyic** [comment]
Thanks for the interest, yes, we will release the library to the public in the coming months. Currently busy in preparing tutorials, documentations, business related stuffs, etc.

**Comment by tianyic** [comment]
Thanks for the interest and patience. OTOv2 has been released. More tutorials and documentations are coming.
