### ISSUE TITLE
Meaning of omega in compute_group_sparsity_omega( )

### ISSUE THREAD

**Issue by flavio-martinelli** [tianyic/only_train_once#41]
Hey! Thanks for publishing such a nice package to perform the experiments of your paper.

I am doing some experiments with OTO and was wondering what is the meaning of your omega metric and how exactly it is formulated. I can't quite grasp it from your code.

**Comment by tianyic** [comment]
@flavio-martinelli  Thanks for reaching out. Omega is referring to l2-norm of all trainable variables in one minimally removal structure or ZIG. 

Our internal OTO renamed it as norm_param to be more self-explained. It will be released by the **end of this month** with significant major updates and improvements.
