### ISSUE TITLE
Get pytorch model prune shape

### ISSUE THREAD

**Issue by C0NGTRI123** [tianyic/only_train_once#42]
Help me. When I run your code with vgg16, I take model pytorch and onnx (pytorch keep the original shape, and onnx prune shape). I want to config quantization use pytorch, not from onnx. How I can take model pytorch has been prune shape to config quantization from pytorch. Thank you

**Comment by tianyic** [comment]
Thanks for reaching out. @C0NGTRI123 Please await for our next major release for OTOv3, expecting within two weeks, 

In this release, the pruned model will be generated in torch format.
