### ISSUE TITLE
How to load compressed model ?

### ISSUE THREAD

**Issue by WYYAHYT** [tianyic/only_train_once#51]
The compressed model can't be loaded with the origin model shape, so the compressed model can't be applied, it can only be used to check accuracy after training.

Maybe the shape of compressed model can be saved for building corresponding model class.

**Comment by tianyic** [comment]
Thanks for reaching out. You may find the solution, the compressed model can be directly loaded in most cases

```python
compressed_model = torch.load(compressed_model_path)
```

Please note that there are some occasional cases that torch can not directly load model. In such case, we provide `ckpt_format='onnx'` to yield compressed model in `onnx` format. 

```python
oto.construct_subnet(
            out_dir=OUT_DIR,
            ckpt_format='onnx'
        )
```

See [test_yolo_v5](https://github.com/tianyic/only_train_once/blob/main/sanity_check/test_yolov5.py).
