### ISSUE TITLE
Can not prune YOLOv8 model

### ISSUE THREAD

**Issue by hoangtv2000** [tianyic/only_train_once#59]
Hi @tianyic,
Im trying to prune this model by hesso optimizer, but the compressed model's size is equal to the original model.
I try to use a different dataset (larger and more diverse) and different scale of target group sparsity (min is 0.1). But the problem is not solved.
I doubt my model architecture is not prunable, because each ZIG set has only 1 convolution layer.

[DetectionModel_pruning_dependency.pdf](https://github.com/tianyic/only_train_once/files/14751167/DetectionModel_pruning_dependency.pdf)

**Comment by tianyic** [comment]
@hoangtv2000 Thanks for reaching out. We will release an update to support Yolov8 soon. The key is to tackle `split` or `slice` operator.

**Comment by hoangtv2000** [comment]
Hi @tianyic, 
I trained my model for a few epochs and reach the target group sparsity at epoch 16. But when I compress the model obtained in epoch 26 by oto.construct_subnet, the output model size (50MB) is equal to the original model. Will I have to train full epochs and the obtained best model can be pruned?

Below is my training setting.

NUM_EPOCHS = 60

target_group_sparsity = 0.35
start_pruning_step = 10
pruning_periods = 5
pruning_steps = 5
