### ISSUE TITLE
TypeError: 'torch._C.Node' object is not subscriptable

### ISSUE THREAD

**Issue by visionKinger** [tianyic/only_train_once#6]
im using torch==1.13.1

and the code run in : op_params = {k: torch_node[k] for k in torch_node.attributeNames()} 
            # op_params = {k: torch_node[k] for k in torch_node.attributeNames()} 
            
            # op_params = {k: getattr(torch_node.schema, k) for k in torch_node.attributeNames()}
            # op_params = {k: torch_node.attribute(k) for k in torch_node.attributeNames()} 
it will generate the bug:TypeError: 'torch._C.Node' object is not subscriptable

as listed, i use other method to get the graph, but all failed

**Comment by tianyic** [comment]
Could you please share the model file?

**Comment by visionKinger** [comment]
im using the yolov7-lite-s.pt in this repo:

> https://github.com/derronqi/yolov7-face

**Comment by tianyic** [comment]
Thanks for sharing. Will take a look upon bandwidth. Please expect perhaps slow response due to heavy duties.

**Comment by visionKinger** [comment]
Sure thank you

**Comment by aksenventwo** [comment]
@visionKinger  try this:

```python
op_params  = {k: getattr(node, node.kindOf(k))(k) for k in  torch_node.attributeNames()}
```

**Comment by tianyic** [comment]
> ```python
> op_params  = {k: getattr(torch_node, torch_node.kindOf(k))(k) for k in  torch_node.attributeNames()}
> ```

Thanks for this fix. Working on my side under torch 2.0. Do you want to create a PR regarding it?

**Comment by visionKinger** [comment]
thank you, I'll try it
