### ISSUE TITLE
ONNX opset setting

### ISSUE THREAD

**Issue by unique-null** [tianyic/only_train_once#7]
Hi @tianyic , 

    I run OTO on my project. However, there is an error which describe "RuntimeError: Exporting the operator im2col to ONNX opset version 9 is not supported. Support for this operator was added in version 11, try exporting with this version.". 
   I use pytorch 1.10.1, which supports opset=13. However, I didn't find the interface for setting the opset. How can I fix the problem.

thx.

**Comment by tianyic** [comment]
Thanks for reaching out. We will add interface to support nonzero version into the next release.

For a hotfix, I suggest to dive into the compression.py in only_train_once/compression

There exist the onnx export functions.

**Comment by unique-null** [comment]
Hi @tianyic ,

    Thanks for  your reply. I checked the ***compression.py***, and I found that current arch only supported ***one input***? How to support the ***multi-input*** model.
![2023-03-24_14-38](https://user-images.githubusercontent.com/40239544/227445073-7d1af181-dac9-4bec-8c66-972d6f5657a0.png)
