### ISSUE TITLE
How to resume?

### ISSUE THREAD

**Issue by rotorliu** [tianyic/only_train_once#9]
Hi, @tianyic 
I run OTO on my project. However, there is an error which describe "ValueError: loaded state dict has a different number of parameter groups" while the train resumes from checkpoint.

**Comment by tianyic** [comment]
Thanks for reaching out. 

Resume can be conducted as the below.

```python
model = torch.load(checkpoint_path)
dummy_input = sth
oto = OTO(model=model, dummy_input=sth)
optimizer = oto.dhspg(
   # set lr, start_pruning  as normal
   fixed_zero_groups=True # if want to preserve the learnt group sparsity from previous training round. 
)

```

**Comment by rotorliu** [comment]
I make a pull request about resuming.
https://github.com/tianyic/only_train_once/pull/11

**Comment by tianyic** [comment]
Thanks for the PR!
